services:
  db:
    image: postgres:15
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: postgresql
      POSTGRES_PASSWORD: dayana
      POSTGRES_DB: holamundo
    ports:
      - "5432:5432"
    volumes:
      - ./bd/init.sql:/docker-entrypoint-initdb.d/init.sql

  backend:
    build: ./backend
    image: class-work-backend:latest
    container_name: backend_app
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - db

  frontend:
    build: ./frontend
    image: class-work-frontend:latest
    container_name: frontend_app
    restart: always
    ports:
      - "8080:80"
    depends_on:
      - backend
