services:
  db:
    image: dayanaheredia/class-work-db:latest
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: postgresql
      POSTGRES_PASSWORD: dayana
      POSTGRES_DB: holamundo
    ports:
      - "5432:5432"

  backend:
    image: dayanaheredia/class-work-backend:latest
    container_name: backend_app
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - db

  frontend:
    image: dayanaheredia/class-work-frontend:latest
    container_name: frontend_app
    restart: always
    ports:
      - "8080:80"
    depends_on:
      - backend
